In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
list_1 = [1, 2, 3, 4, 5]
print(list_1)

[1, 2, 3, 4, 5]


In [6]:
print(np.__version__)

1.26.4


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
# 0-dimension (0-d)
d_0 = np.array(42)

print(d_0)

42


In [9]:
d_1 = np.array([1, 2, 3, 4, 5])

print(d_1)

[1 2 3 4 5]


In [10]:
d_2 = np.array([[1, 2, 3], [4, 5, 6]])

print(d_2)

[[1 2 3]
 [4 5 6]]


In [11]:
d_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(d_3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
e = np.array([1, 2, 3, 4], ndmin=5)

print(e)
print('number of dimensions :', e.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
